# Generated by Django 3.2.9 on 2021-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mod',
            field=models.BooleanField(default=False, help_text="Designates whether this user can create a ViViPlayer's session.", verbose_name='moderator status'),
        ),
    ]
