# Generated by Django 3.2.9 on 2021-12-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_mod',
        ),
    ]
