version: '3'

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  django:
    build: ./viviplayer
    volumes:
      - ./viviplayer:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
  frontend:
    build: ./viviplayer-frontend
    volumes:
      - ./viviplayer-frontend:/app/frontend
    ports:
      - "3000:3000"

