version: '3'

services:
  django:
    build: ./viviplayer
    container_name: vivipl3_backend
    environment:
      - VIVIMODE=dev
    volumes:
      - ./viviplayer:/app/backend
    ports:
      - "8000:8000"
  frontend:
    build: ./viviplayer-frontend
    container_name: vivipl3_frontend
    environment:
      - VIVIMODE=dev
    volumes:
      - next_cache:/app/frontend/.next
      - ./viviplayer-frontend:/app/frontend
    ports:
      - "3000:3000"
volumes:
  next_cache:
