version: '3'

services:
  redis:
    image: redis:5
    container_name: vivipl3_redis
    expose:
      - "6379"
  django:
    build: ./viviplayer
    container_name: vivipl3_backend
    volumes:
      - ./viviplayer:/app/backend
    ports:
      - "8000:8000"
    links:
      - redis
  frontend:
    build: ./viviplayer-frontend
    container_name: vivipl3_frontend
    volumes:
      - next_cache:/app/frontend/.next
      - ./viviplayer-frontend:/app/frontend
    ports:
      - "3000:3000"
volumes:
  next_cache:
