import React from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';

const Dashboard = (props) => {
  return (
    <div>
      <Head>
        <title>Viviplayer 3 - Dashboard</title>
        <meta name="description" content="Generated by Viviplayer3 Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 style={{ fontSize: '50px', textAlign: 'center', paddingTop: '200px' }}>
        LOGIN SUCCESS Dashboard
      </h2>
    </div>
  );
};

Dashboard.propTypes = {};

export default Dashboard;
