import Head from "next/head";
import { Form, Input, Button, Checkbox } from "antd";

export default function Home() {
  const onFinish = (values) => {
    console.log("Success:", values);
  };

  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };

  return (
    <div>
      <Head>
        <title>Viviplayer 3 - Login</title>
        <meta name="description" content="Generated by Viviplayer3 Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-image"></div>

      <div className="bg-text">
        <h2>Viviplayer</h2>
        
      </div>
    </div>
  );
}
