import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Router from 'next/router';
import { Form, Input, Tabs, Button, Checkbox } from 'antd';
import NumberOutlined from '@ant-design/icons/NumberOutlined';
import { login, loadUser } from '../actions/auth.actions';

const { TabPane } = Tabs;
export default function Home() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  useEffect(async () => {
    if (localStorage.getItem('user') !== null) {
      setIsAuthenticated(true);
    }
  }, []);
  const onFinish = async ({ username, password }) => {
    let a = await login(username.trim(), password.trim());
    if (a === true) {
      setIsAuthenticated(true);
    }
  };
  const loginWithTan = (values) => {
    console.log('TAN VALUES', values.tan);
    if (values.tan !== '112021') {
      console.log('run here');
      openNotification('TAN is not correct!');
    } else {
      Router.push('/dashboard');
    }
  };
  if (isAuthenticated) {
    Router.push('/dashboard');
  }

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };
  function callback(key) {
    console.log(key);
  }
  return (
    <div>
      <Head>
        <title>Viviplayer 3 - Login</title>
        <meta name="description" content="Generated by Viviplayer3 Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-image"></div>

      <div className="bg-text">
        <Tabs defaultActiveKey="1" onChange={callback}>
          <TabPane tab="Login with TAN" key="1" className="text-white">
            <Form name="TAN Login" onFinish={loginWithTan} autoComplete="off">
              <Form.Item style={{ marginBottom: '1em' }} name="tan">
                <Input prefix={<NumberOutlined />} placeholder="TAN" />
              </Form.Item>
              <Button type="primary" htmlType="submit">
                Submit
              </Button>
            </Form>
          </TabPane>
          <TabPane tab="Login as Moderator" key="2" className="text-white">
            <Form
              name="loginForm"
              labelCol={{
                span: 5
              }}
              wrapperCol={{
                span: 17
              }}
              initialValues={{
                remember: true
              }}
              onFinish={onFinish}
              onFinishFailed={onFinishFailed}
              autoComplete="off"
            >
              <Form.Item className="form-login-label" label="Username" name="username">
                <Input />
              </Form.Item>

              <Form.Item className="form-login-label" label="Password" name="password">
                <Input.Password />
              </Form.Item>
              <Form.Item
                name="remember"
                valuePropName="checked"
                wrapperCol={{
                  offset: 5,
                  span: 16
                }}
              >
                <Checkbox className="text-white">Remember me</Checkbox>
              </Form.Item>

              <Form.Item
                wrapperCol={{
                  offset: 5,
                  span: 16
                }}
              >
                <Button type="primary" htmlType="submit">
                  Submit
                </Button>
              </Form.Item>
            </Form>
          </TabPane>
        </Tabs>
      </div>
    </div>
  );
}
