import React, { useEffect } from 'react';
import Head from 'next/head';
import Router from 'next/router';
import { Form, Input, Tabs, Button, Checkbox } from 'antd';
import NumberOutlined from '@ant-design/icons/NumberOutlined';
import { Notification } from '../utils/notification';
import { connect } from 'react-redux';
import { login, loadUser } from '../actions/auth.action';
import setAuthToken from '../utils/setAuthToken';

const { TabPane } = Tabs;
const Home = ({ isAuthenticated, login, loadUser }) => {
  useEffect(() => {
    // check for token in LS when app first runs
    if (localStorage.token) {
      // if there is a token set axios headers for all requests
      setAuthToken(localStorage.token);
    }
    // try to fetch a user, if no token or invalid token we
    // will get a 401 response from our API
    loadUser();

    // log user out from all tabs if they log out in one tab
    // window.addEventListener('storage', () => {
    //   if (!localStorage.token) {
    //     type: LOGOUT;
    //   }
    // });
  }, []);
  // Login API
  const onFinish = async ({ username, password }) => {
    console.log('Login VIEW', username, password);
    login(username.trim(), password.trim());
  };

  const loginWithTan = (values) => {
    console.log('TAN VALUES', values.tan);
    // if (values.tan !== '112021') {
    //   console.log('run here');
    //   Notification('Login', 'TAN is not correct!');
    // } else {
    //   Router.push('/dashboard');
    // }
  };

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };
  function callback(key) {
    console.log(key);
  }
  if (isAuthenticated) {
    Router.push('/dashboard');
  }
  return (
    <div>
      <Head>
        <title>Viviplayer 3 - Login</title>
        <meta name="description" content="Generated by Viviplayer3 Team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-image"></div>

      <div className="bg-text">
        <Tabs defaultActiveKey="1" onChange={callback}>
          <TabPane tab="Login with TAN" key="1" className="text-white">
            <Form name="TAN Login" onFinish={loginWithTan} autoComplete="off">
              <Form.Item style={{ marginBottom: '1em' }} name="tan">
                <Input prefix={<NumberOutlined />} placeholder="TAN" />
              </Form.Item>
              <Button type="primary" htmlType="submit">
                Submit
              </Button>
            </Form>
          </TabPane>
          <TabPane tab="Login as Moderator" key="2" className="text-white">
            <Form
              name="loginForm"
              labelCol={{
                span: 5
              }}
              wrapperCol={{
                span: 17
              }}
              initialValues={{
                remember: true
              }}
              onFinish={onFinish}
              onFinishFailed={onFinishFailed}
              autoComplete="off"
            >
              <Form.Item className="form-login-label" label="Username" name="username">
                <Input />
              </Form.Item>

              <Form.Item className="form-login-label" label="Password" name="password">
                <Input.Password />
              </Form.Item>
              <Form.Item
                name="remember"
                valuePropName="checked"
                wrapperCol={{
                  offset: 5,
                  span: 16
                }}
              >
                <Checkbox className="text-white">Remember me</Checkbox>
              </Form.Item>

              <Form.Item
                wrapperCol={{
                  offset: 5,
                  span: 16
                }}
              >
                <Button type="primary" htmlType="submit">
                  Submit
                </Button>
              </Form.Item>
            </Form>
          </TabPane>
        </Tabs>
      </div>
    </div>
  );
};
const mapStateToProps = (state) => ({
  isAuthenticated: state.auth.isAuthenticated
});

export default connect(mapStateToProps, { login, loadUser })(Home);
