# Generated by Django 3.2.9 on 2021-12-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_sentence', to='session.shot'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_userstory', to='session.shot'),
        ),
    ]
