# Generated by Django 3.2.9 on 2021-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='vivisession',
            name='tan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vivisession',
            name='video_path',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
