# Generated by Django 3.2.9 on 2022-01-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_shot_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='desc',
            new_name='moechteichals2',
        ),
        migrations.RemoveField(
            model_name='vivisession',
            name='current_users',
        ),
        migrations.AddField(
            model_name='userstory',
            name='damit',
            field=models.CharField(default='leer', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='moechteichals1',
            field=models.CharField(default='leer', max_length=500),
            preserve_default=False,
        ),
    ]
