# Generated by Django 3.2.9 on 2021-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20211209_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='desc',
            new_name='text',
        ),
    ]
