# Generated by Django 3.2.9 on 2022-01-13 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import session.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0003_auto_20220106_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('typeOfQuestion', models.CharField(choices=[('question', 'Question'), ('survey', 'Survey')], max_length=10)),
                ('typeToRender', models.CharField(choices=[('checkbox', 'Checkbox'), ('radiotype', 'Radiotype')], max_length=10)),
                ('choices', models.JSONField(default=session.models.get_default_json_for_question)),
                ('answers', models.JSONField(default=session.models.get_default_json_for_question)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='shot',
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['id'], 'verbose_name': 'Sentence', 'verbose_name_plural': 'Sentences'},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['time'], 'verbose_name': 'Shot', 'verbose_name_plural': 'Shots'},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['id'], 'verbose_name': 'UserStory', 'verbose_name_plural': 'UserStories'},
        ),
        migrations.AlterModelOptions(
            name='vivisession',
            options={'ordering': ['id'], 'verbose_name': 'ViViSession', 'verbose_name_plural': 'ViViSessions'},
        ),
        migrations.AlterField(
            model_name='sentence',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='session.vivisession'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='session.shot'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='session.vivisession'),
        ),
        migrations.AddField(
            model_name='question',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='session.shot'),
        ),
    ]
