export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const LOGIN_SUCCESS_WITH_TAN = 'LOGIN_SUCCESS_WITH_TAN';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAIL = 'CREATE_SESSION_FAIL';
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_FAIL = 'GET_SESSION_FAIL';
// Sentences
export const GET_SENTENCES_SUCCESS = 'GET_SENTENCES_SUCCESS';
export const GET_SENTENCES_FAIL = 'GET_SENTENCES_FAIL';
export const CREATE_SENTENCES_SUCCESS = 'CREATE_SENTENCES_SUCCESS';
export const CREATE_SENTENCES_FAIL = 'CREATE_SENTENCES_FAIL';
export const GET_SENTENCE_BY_ID = 'GET_SENTENCE_BY_ID';
export const GET_SENTENCE_BY_ID_FAIL = 'GET_SETTENCE_BY_ID_FAIL';
export const UPDATE_SENTENCE_BY_ID = 'UPDATE_SENTENCE_BY_ID';
export const UPDATE_SENTENCE_BY_ID_FAIL = 'UPDATE_SETTENCE_BY_ID_FAIL';
export const DELETE_SENTENCE_SUCCESS = 'DELETE_SENTENCE_SUCCESS';
export const DELETE_SENTENCE_SUCCESS_FAIL = 'DELETE_SENTENCE_SUCCESS_FAIL';

// User Stories
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY_FAIL = 'GET_STORY_FAIL';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_FAIL = 'CREATE_STORY_FAIL';
export const GET_STORY_BY_ID = 'GET_STORY_BY_ID';
export const GET_STORY_BY_ID_FAIL = 'GET_STORY_BY_ID_FAIL';
export const UPDATE_STORY_BY_ID = 'UPDATE_STORY_BY_ID';
export const UPDATE_STORY_BY_ID_FAIL = 'UPDATE_STORY_BY_ID_FAIL';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_STORY_SUCCESS_FAIL = 'DELETE_STORY_SUCCESS_FAIL';
