export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const LOGIN_WITH_TAN_SUCCESS = 'LOGIN_WITH_TAN_SUCCESS';
export const LOGIN_WITH_TAN_FAIL = 'LOGIN_WITH_TAN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAIL = 'CREATE_SESSION_FAIL';

// SESSION
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_FAIL = 'GET_SESSION_FAIL';
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS';
export const UPDATE_SESSION_FAIL = 'UPDATE_SESSION_FAIL';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_FAIL = ' DELETE_SESSION_FAIL';

// Sentences
export const GET_SENTENCES_SUCCESS = 'GET_SENTENCES_SUCCESS';
export const GET_SENTENCES_FAIL = 'GET_SENTENCES_FAIL';
export const CREATE_SENTENCES_SUCCESS = 'CREATE_SENTENCES_SUCCESS';
export const CREATE_SENTENCES_FAIL = 'CREATE_SENTENCES_FAIL';
export const GET_SENTENCE_BY_ID = 'GET_SENTENCE_BY_ID';
export const GET_SENTENCE_BY_ID_FAIL = 'GET_SETTENCE_BY_ID_FAIL';
export const UPDATE_SENTENCE_BY_ID = 'UPDATE_SENTENCE_BY_ID';
export const UPDATE_SENTENCE_BY_ID_FAIL = 'UPDATE_SETTENCE_BY_ID_FAIL';
export const DELETE_SENTENCE_SUCCESS = 'DELETE_SENTENCE_SUCCESS';
export const DELETE_SENTENCE_SUCCESS_FAIL = 'DELETE_SENTENCE_SUCCESS_FAIL';
// UserStory
export const GET_ALL_USERSTORIRES_SUCCESS = 'GET_ALL_USERSTORIRES_SUCCESS';
export const GET_ALL_USERSTORIRES_FAILS = 'GET_ALL_USERSTORIRES_FAIL';
export const CREATE_USERSTORY_SUCCESS = 'CREATE_USERSTORY_SUCCESS';
export const CREATE_USERSTORY_FAIL = 'CREATE_USERSTORY_FAIL';
export const UPDATE_USERSTORY_SUCCESS = 'UPDATE_USERSTORY_SUCCESS';
export const UPDATE_USERSTORY_FAIL = 'UPDATE_USERSTORY_FAIL';
export const GET_USERSTORY_BY_ID_SUCCESS = 'GET_USERSTORY_BY_ID';
export const GET_USERSTORY_BY_ID_FAIL = 'GET_USERSTORY_BY_ID_FAIL';
export const DELETE_USERSTORY_BY_ID_SUCCESS = 'DELETE_USERSTORY_BY_ID_SUCCESS';
export const DELETE_USERSTORY_SUCCESS_FAIL = 'DELETE_SENTENCE_SUCCESS_FAIL';
